const mongoose = require("mongoose");

const LikeSchema = new mongoose.Schema({
  like_nums: Number,
  parent: mongoose.Types.ObjectId, // primary key of parent's _id of project auto generated by Mongoose
});

module.exports = mongoose.model("like", LikeSchema);
